project:
  type: website
  output-dir: docs

website:
  title: "Mark Baillie"
  site-url: https://bailliem.github.io
  description: "Striving to be useful"
  page-navigation: false
  
  repo-url: https://github.com/bailliem.github.io
  repo-actions: [edit, issue]
  
  # page-footer:
  #   left: "This page is written with [Quarto](https://quarto.org/)."
  #   background: "#ffffff"
  #   right:
  #   - text: "License"
  #     href: LICENSE.md
      
  navbar:
    background: "#ffffff"
    align: center
    title: "Mark Baillie"

    left: 
      - href: index.qmd
        text: home
      - href: posts/index.qmd
        text: notes
    right:
      - icon: github
        href: https://github.com/bailliem
      - icon: linkedin
        href: https://www.linkedin.com/in/bailliem

format:
  html:
    theme: yeti #cosmo 
    toc: true
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto