project:
  type: website
  output-dir: docs

website:
  title: "Mark Baillie"
  site-url: https://bailliem.github.io
  description: "Tiny changes"
  page-navigation: false
  
  page-footer:
    left: "This page is produced with [Quarto](https://quarto.org/)."
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/bailliem/
      - icon: github
        href: https://github.com/bailliem
      - text: "License"
        href: LICENSE.md
  
  repo-url: https://github.com/bailliem.github.io
  repo-actions: [edit, issue]
  
  navbar:
    background: "#ffffff"
    align: left
    title: "Mark Baillie"

    left: 
      - href: about.qmd
        text: about
      - href: projects.qmd
        text: projects
      - href: posts/index.qmd
        text: notes
    right:
      - icon: github
        href: https://github.com/bailliem
      - icon: linkedin
        href: https://www.linkedin.com/in/bailliem

format:
  html:
    theme: cosmo #yeti #cosmo #solar 
    toc: true
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto