project:
  type: website
  output-dir: docs

website:
  title: "Mark Baillie"
  site-url: https://bailliem.github.io
  description: "Work in progress"
  navbar:
    right:
      - icon: github
        href: https://github.com/bailliem
      - icon: linkedin
        href: https://www.linkedin.com/in/mark-baillie-52486735/
      - about.qmd
format:
  html:
    theme: yeti
    css: styles.css
    code-tools:
      source: true
      toggle: true
      caption: none

editor: visual

execute:
  freeze: auto